### ISSUE TITLE
needs to import stuff from `SummarizedExperiment`?

### ISSUE THREAD

**Issue by andrewejaffe** [leekgroup/recount#1]
couldn't get raw gene counts out of `rse_gene` object, needed to load `library(SummarizedExperiment)`

**Comment by lcolladotor** [comment]
See Martin Morgan's comment at https://github.com/Bioconductor/Contributions/issues/9#issuecomment-228533667. Which is why now `SummarizedExperiment` is in the `Depends:` field.
