### ISSUE TITLE
Is additional normalization needed when compare counts between two different projects, like TCGA and GTEx?

### ISSUE THREAD

**Issue by xiaodongpang23** [leekgroup/recount#13]
I would like to compare the distribution of gene expression between samples from TCGA and GTEx. So I download the RSE from TCGA and GTEx and do scale_counts and combine two data set together for histogram plots. So after combing the two data set, do I need to do additional normalization for comparison?
Thanks

**Comment by lcolladotor** [comment]
Hi,

Sorry that I missed this question a while back. In any case, the answer is complicated as normalization across projects is an active area of research. @kasperdanielhansen and others might have more detailed information for you. 

As a starting point, check Supplementary File 3 from https://www.biorxiv.org/content/10.1101/618025v1 written by @ShanEllis.

Best,
Leonardo
