### ISSUE TITLE
How to get annotation for exon? 

### ISSUE THREAD

**Issue by ahdee** [leekgroup/recount#17]
Hi so there is an option to download rse-exon, however I don't understand how the annotation works.  For example, here is how KRAS which only has 6 exons look like. 
**edit**: specifically I'm intereted in reconstructing from version two if this is even possible? 
```
download_study("DRP001219", type = "rse-exon", outdir="./data/")
load(file.path( "./data/rse_exon.Rdata"))
count = assays(rse_exon)$counts
count[ grepl("ENSG00000133703", row.names(count)), , drop=F]

                   DRR014113
ENSG00000133703.11     78483
ENSG00000133703.11      4095
ENSG00000133703.11      5518
ENSG00000133703.11       388
ENSG00000133703.11      2350
ENSG00000133703.11      5462
ENSG00000133703.11      1972
ENSG00000133703.11      2725
ENSG00000133703.11       235
ENSG00000133703.11      1108
ENSG00000133703.11      2495
ENSG00000133703.11         0
ENSG00000133703.11         0
```

So how would I know what is for exon 1, 2 or 3? There is an object call recount_exon but that only gives the coordinates.

**Comment by lcolladotor** [comment]
Hi @ahdee,

You could look into `recount::reproduce_ranges()` to do this as the answer lies in https://github.com/leekgroup/recount/blob/master/R/reproduce_ranges.R#L77-L80.

You'll likely need to keep the original exons before doing the disjoin step at https://github.com/leekgroup/recount/blob/master/R/reproduce_ranges.R#L89 and then matching them back through functions from the GenomicRanges Bioconductor package.

I realize that this is complicated. We'll do this in a different way for the next version of the recount project coming soon-ish.

Best,
Leo
