### ISSUE TITLE
Issue downloading the recount package with my version of R 

### ISSUE THREAD

**Issue by julclu** [leekgroup/recount#2]
Hi there, 

I have read the instructions for downloading the recount R package, and it says first to upgrade R to version 3.3.0. At the CRAN website, I recently upgraded my version of R to 3.3.1; however, it seems that biocLite is unable to download recount under this newer version. Am I doing something wrong?

Here is the error:  

> biocLite('recount')
> BioC_mirror: https://bioconductor.org
> Using Bioconductor 3.3 (BiocInstaller 1.22.3), R 3.3.1 (2016-06-21).
> Installing package(s) ‘recount’
> Warning message:
> package ‘recount’ is not available (for R version 3.3.1) 

Thanks for your help in advance.

**Comment by lcolladotor** [comment]
Hi @julclu,

You are using the release version of Bioconductor (version 3.3). `recount` is currently only available for the development version of Bioconductor (version 3.4). See https://www.bioconductor.org/developers/how-to/useDevel/ for instructions on how to use Bioconductor devel.

Best,
Leonardo

**Comment by julclu** [comment]
Thank you for your prompt response Leonardo! I'm excited to start using recount.
